
import React, { useEffect, useState } from 'react';
import { Alert, Button, Card, Descriptions, Drawer, Form, Input, InputNumber, Modal, Select, Space, Switch, Table, Tag, Typography, message } from 'antd';
import { AppstoreOutlined, SettingOutlined, FileTextOutlined, TeamOutlined, WalletOutlined, GiftOutlined, DeploymentUnitOutlined, CloudServerOutlined, SafetyCertificateOutlined, ShoppingCartOutlined } from '@ant-design/icons';
import { AppShell } from '../../shared/frontend/components/AppShell.jsx';
import { MetricCard } from '../../shared/frontend/components/MetricCard.jsx';
import { RoleTopology } from '../../shared/frontend/components/RoleTopology.jsx';
import { StatusBadge } from '../../shared/frontend/components/StatusBadge.jsx';
import { NodeOperationPanel } from '../../shared/frontend/components/NodeOperationPanel.jsx';
import { LogPanel } from '../../shared/frontend/components/LogPanel.jsx';
import { CodeLine } from '../../shared/frontend/components/CopyText.jsx';
import { ApiClient, formatBytes, formatMbps, formatMoney, formatTime } from '../../shared/frontend/api/client.js';

const api = new ApiClient({ tokenKey: 'admin_token' });
const routes = {
  dashboard: ['Master 总览', 'Master Control Plane 运行态和角色拓扑'], settings: ['系统设置', '基础域名、端口池和邮件测试'], logs: ['操作日志', '管理员操作记录'],
  users: ['用户管理', '修改用户状态和套餐'], plans: ['套餐管理', '新增和编辑可售套餐'], payments: ['订单支付', '支付方式绑定入口和订单'], redeem: ['兑换码', '生成兑换码时选择套餐'],
  tunnels: ['隧道管理', '全部用户隧道'], nodes: ['FRPS 节点', '状态、配置、日志、重启、reload'], certificates: ['域名证书', '证书、Nginx 和 CNAME 运维']
};
function route() { return location.hash.replace(/^#\/?/, '') || 'dashboard'; }
function item(key, label, icon, shortLabel) { return { key, label, rawLabel: label, shortLabel: shortLabel || label, icon }; }
function number(v) { return Number(v) || 0; }
function planOptions(plans) { return plans.map(p => ({ value: p.id, label: `${p.name} / ${formatMoney(p.price_cents)}` })); }

function Login({ onAuthed }) {
  const [loading, setLoading] = useState(false);
  async function submit(v) { setLoading(true); try { const data = await api.post('/api/admin/login', v, { token: '' }); api.setToken(data.access_token); onAuthed(); } catch(e) { message.error(e.message); } finally { setLoading(false); } }
  return <div className="auth-layout"><section className="auth-hero"><div className="hero-dots"><i /></div><Typography.Text type="secondary">Admin Console</Typography.Text><Typography.Title>Master 控制面后台</Typography.Title><Typography.Paragraph>管理用户、套餐、订单、节点和证书，对齐 frp-panel 角色架构。</Typography.Paragraph></section><section className="auth-card-wrap"><Card title="管理员登录"><p className="admin-login-note">请使用部署环境中的 ADMIN_EMAIL / ADMIN_PASSWORD。</p><Form layout="vertical" onFinish={submit}><Form.Item name="email" label="Email" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="password" label="Password" rules={[{ required: true }]}><Input.Password /></Form.Item><Button type="primary" htmlType="submit" loading={loading} block>登录后台</Button></Form></Card></section></div>;
}
export default function App() {
  const [current, setCurrent] = useState(route());
  const [data, setData] = useState({ loading: true, loadError: '', admin: null, topology: null, plans: [], users: [], redeem: [], tunnels: [], nodes: [], certs: [], settings: null, payment: null, orders: [], operations: [] });
  const [operation, setOperation] = useState(null);
  useEffect(() => { const f = () => setCurrent(route()); window.addEventListener('hashchange', f); return () => window.removeEventListener('hashchange', f); }, []);
  async function load() {
    if (!api.token()) { setData(d => ({ ...d, loading: false, admin: null })); return; }
    try {
      let partial = false;
      const optional = (promise, fallback) => promise.catch(() => { partial = true; return fallback; });
      const [admin, topology, plans, users, redeem, tunnels, nodes, certs, settings, payment, orders, operations] = await Promise.all([
        api.get('/api/admin/me'), optional(api.get('/api/admin/topology'), null), optional(api.get('/api/admin/plans'), []), optional(api.get('/api/admin/users'), []), optional(api.get('/api/admin/redeem-codes'), []), optional(api.get('/api/admin/tunnels'), []), optional(api.get('/api/admin/nodes'), []), optional(api.get('/api/admin/certificates'), []), optional(api.get('/api/admin/settings'), null), optional(api.get('/api/admin/payment-config'), null), optional(api.get('/api/admin/orders'), []), optional(api.get('/api/admin/operation-logs'), [])
      ]);
      setData({ loading: false, loadError: partial ? '部分后台数据加载失败，请刷新重试' : '', admin, topology, plans, users, redeem, tunnels, nodes, certs, settings, payment, orders, operations });
    } catch(e) { api.setToken(''); setData(d => ({ ...d, loading: false, admin: null })); }
  }
  useEffect(() => { load(); }, []);
  if (!api.token() || !data.admin) return <Login onAuthed={load} />;
  const key = routes[current] ? current : 'dashboard';
  const menu = [
    { type: 'group', label: 'Master', children: [item('dashboard', 'Master 总览', <AppstoreOutlined />, 'Master'), item('settings', '系统设置', <SettingOutlined />, '系统设置'), item('logs', '操作日志', <FileTextOutlined />, '操作日志')] },
    { type: 'group', label: '业务', children: [item('users', '用户管理', <TeamOutlined />, '用户管理'), item('plans', '套餐管理', <WalletOutlined />, '套餐管理'), item('payments', '订单支付', <ShoppingCartOutlined />, '订单支付'), item('redeem', '兑换码', <GiftOutlined />)] },
    { type: 'group', label: '资源', children: [item('tunnels', '隧道管理', <DeploymentUnitOutlined />, '隧道管理'), item('nodes', 'FRPS 节点', <CloudServerOutlined />, '节点管理'), item('certificates', '域名证书', <SafetyCertificateOutlined />, '域名证书')] }
  ];
  return <AppShell title={routes[key][0]} subtitle={routes[key][1]} brand="FRP Admin" brandSub="Master Control" menuItems={menu} selectedKey={key} onSelect={k => { location.hash = k; setCurrent(k); }} onRefresh={load} userLabel={data.admin.email} onLogout={() => { api.setToken(''); location.hash='login'; }} storageKey="adminSidebarCollapsedV4">
    {data.loadError && <Alert type="warning" showIcon message={data.loadError} style={{ marginBottom: 16 }} />}
    {render(key, data, load, operation, setOperation)}
  </AppShell>;
}
function render(key, data, load, operation, setOperation) { const p = { data, load, operation, setOperation }; return ({ dashboard:<Dashboard {...p}/>, settings:<Settings {...p}/>, logs:<Logs {...p}/>, users:<Users {...p}/>, plans:<Plans {...p}/>, payments:<Payments {...p}/>, redeem:<Redeem {...p}/>, tunnels:<Tunnels {...p}/>, nodes:<Nodes {...p}/>, certificates:<Certificates {...p}/> })[key]; }
function Dashboard({ data }) { const t = data.topology || {}; return <div className="panel-stack"><Alert showIcon type="info" message="Master Control Plane" description="Admin Console -> Master -> Server(FRPS) -> Client(FRPC) / Visitor" /><div className="metric-grid"><MetricCard title="用户数" value={t.user_count || 0} /><MetricCard title="有效套餐" value={t.active_subscription_count || 0} /><MetricCard title="隧道数" value={t.tunnel_count || 0} /><MetricCard title="在线 FRPS" value={`${t.online_node_count || 0}/${t.node_count || 0}`} /></div><RoleTopology mode="admin" data={t} /><div className="two-column"><Card title="最近订单" bordered={false}><OrdersTable data={t.recent_orders || []} /></Card><Card title="支付通道" bordered={false}>{(t.payment_methods || []).map(m => <Card key={m.pay_type} size="small" className="payment-method-card" style={{ marginBottom: 10 }}><Descriptions size="small" column={1} items={[{label:'Method',children:m.method},{label:'Channel',children:m.channel},{label:'Status',children:<StatusBadge status={m.online?'online':'disabled'} />}]} /></Card>)}</Card></div></div>; }
function Users({ data, load }) { const [editing, setEditing] = useState(null); const [form] = Form.useForm(); async function save(v){ try { await api.put(`/api/admin/users/${editing.id}`, { status: v.status, plan_id: v.plan_id || 0 }); message.success('用户已更新'); setEditing(null); load(); } catch(e){ message.error(e.message); } } return <Card bordered={false} className="page-card"><Table rowKey="id" dataSource={data.users} columns={[{title:'ID',dataIndex:'id'},{title:'Email',dataIndex:'email'},{title:'Status',dataIndex:'status',render:v=><StatusBadge status={v}/>},{title:'Created',dataIndex:'created_at',render:formatTime},{title:'Action',render:(_,r)=><Button onClick={()=>{setEditing(r); form.setFieldsValue({status:r.status});}}>修改套餐</Button>}]} /><Drawer open={!!editing} onClose={()=>setEditing(null)} title="修改用户" width={460}><Form form={form} layout="vertical" onFinish={save}><Form.Item name="status" label="Status"><Select options={['active','disabled'].map(v=>({value:v,label:v}))}/></Form.Item><Form.Item name="plan_id" label="指定套餐"><Select allowClear options={planOptions(data.plans)} /></Form.Item><Button type="primary" htmlType="submit">保存</Button></Form></Drawer></Card>; }
function planPayload(v){ const gb = 1024*1024*1024; return { ...v, price_cents:number(v.price_cents), duration_days:number(v.duration_days), traffic_limit_bytes:number(v.traffic_gb)*gb, bandwidth_limit_kbps:number(v.bandwidth_mbps)*1000, max_tunnels:number(v.max_tunnels), max_tcp_tunnels:number(v.max_tcp_tunnels), max_udp_tunnels:number(v.max_udp_tunnels), max_http_tunnels:number(v.max_http_tunnels), max_https_tunnels:number(v.max_https_tunnels), max_domains:number(v.max_domains), allow_tcp:!!v.allow_tcp, allow_udp:!!v.allow_udp, allow_http:!!v.allow_http, allow_https:!!v.allow_https, allow_custom_domain:!!v.allow_custom_domain, allow_auto_cert:!!v.allow_auto_cert, status:v.status || 'active' }; }
function planFormValues(p){ if(!p) return { status:'active', duration_days:30, traffic_gb:100, bandwidth_mbps:10, max_tunnels:20, max_tcp_tunnels:10, max_udp_tunnels:10, max_http_tunnels:10, max_https_tunnels:10, max_domains:10, allow_tcp:true, allow_udp:true, allow_http:true, allow_https:true, allow_custom_domain:true, allow_auto_cert:true }; return { ...p, traffic_gb: Math.round((p.traffic_limit_bytes||0)/1024/1024/1024), bandwidth_mbps: Math.round((p.bandwidth_limit_kbps||0)/1000) }; }
function Plans({ data, load }) { const [open,setOpen]=useState(false); const [editing,setEditing]=useState(null); const [form]=Form.useForm(); function edit(p){setEditing(p); form.setFieldsValue(planFormValues(p)); setOpen(true);} async function save(v){ try{ const payload=planPayload(v); if(editing) await api.put(`/api/admin/plans/${editing.id}`, payload); else await api.post('/api/admin/plans', payload); message.success('套餐已保存'); setOpen(false); setEditing(null); load(); }catch(e){message.error(e.message);} } return <Card bordered={false} className="page-card"><div className="table-toolbar"><Alert showIcon type="info" message="套餐支持新增和修改" /><Button type="primary" onClick={()=>edit(null)}>新增套餐</Button></div><Table rowKey="id" dataSource={data.plans} columns={[{title:'ID',dataIndex:'id'},{title:'名称',dataIndex:'name'},{title:'价格',dataIndex:'price_cents',render:formatMoney},{title:'流量',dataIndex:'traffic_limit_bytes',render:formatBytes},{title:'带宽',dataIndex:'bandwidth_limit_kbps',render:formatMbps},{title:'Status',dataIndex:'status',render:v=><StatusBadge status={v}/>},{title:'Action',render:(_,r)=><Button onClick={()=>edit(r)}>编辑</Button>}]} /><Drawer open={open} onClose={()=>setOpen(false)} title={editing?'编辑套餐':'新增套餐'} width={620}><Form form={form} layout="vertical" onFinish={save}><Form.Item name="name" label="名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="description" label="描述"><Input.TextArea/></Form.Item><Space wrap><Form.Item name="price_cents" label="价格（分）"><InputNumber/></Form.Item><Form.Item name="duration_days" label="天数"><InputNumber/></Form.Item><Form.Item name="traffic_gb" label="GB"><InputNumber/></Form.Item><Form.Item name="bandwidth_mbps" label="Mbps"><InputNumber/></Form.Item><Form.Item name="max_tunnels" label="隧道"><InputNumber/></Form.Item></Space><Space wrap>{['allow_tcp','allow_udp','allow_http','allow_https','allow_custom_domain','allow_auto_cert'].map(k=><Form.Item key={k} name={k} label={k} valuePropName="checked"><Switch/></Form.Item>)}</Space><Space wrap>{['max_tcp_tunnels','max_udp_tunnels','max_http_tunnels','max_https_tunnels','max_domains'].map(k=><Form.Item key={k} name={k} label={k}><InputNumber/></Form.Item>)}</Space><Form.Item name="status" label="Status"><Select options={['active','disabled'].map(v=>({value:v,label:v}))}/></Form.Item><Button type="primary" htmlType="submit">保存</Button></Form></Drawer></Card>; }
function Payments({ data }) { return <div className="panel-stack"><Alert showIcon type={data.payment?.enabled?'success':'warning'} message="支付方式绑定入口" description="支付方式 -> pay_type -> channel 的映射在这里可见。" /><div className="card-grid">{(data.payment?.methods||[]).map(m=><Card key={m.pay_type} title={m.method} bordered={false}><Descriptions column={1} items={[{label:'Provider',children:m.provider},{label:'Channel',children:m.channel},{label:'pay_type',children:m.pay_type},{label:'API',children:<CodeLine text={m.api_base}/>}]} /></Card>)}</div><Card title="订单" bordered={false}><OrdersTable data={data.orders}/></Card></div>; }
function OrdersTable({ data }) { return <Table size="small" rowKey="out_trade_no" dataSource={data||[]} pagination={{pageSize:8}} columns={[{title:'ID',dataIndex:'id'},{title:'User',dataIndex:'user_id'},{title:'Plan',dataIndex:'plan_id'},{title:'No',dataIndex:'out_trade_no',render:v=><CodeLine text={v}/>},{title:'Type',dataIndex:'pay_type'},{title:'Money',dataIndex:'money'},{title:'Status',dataIndex:'status',render:v=><StatusBadge status={v}/>},{title:'Time',dataIndex:'created_at',render:formatTime}]} />; }
function Redeem({ data, load }) { const [form]=Form.useForm(); async function gen(v){ try{ const codes=await api.post('/api/admin/redeem-codes', v); Modal.success({title:'生成成功', content:<pre>{codes.map(c=>c.code).join('\n')}</pre>}); form.resetFields(); load(); }catch(e){message.error(e.message);} } return <div className="two-column"><Card title="生成兑换码" bordered={false}><Form form={form} layout="vertical" onFinish={gen} initialValues={{count:1,prefix:'PLAN'}}><Form.Item name="plan_id" label="绑定套餐" rules={[{required:true}]}><Select options={planOptions(data.plans)}/></Form.Item><Form.Item name="count" label="数量"><InputNumber min={1} max={500}/></Form.Item><Form.Item name="prefix" label="前缀"><Input/></Form.Item><Button type="primary" htmlType="submit">生成</Button></Form></Card><Card title="兑换码列表" bordered={false}><Table size="small" rowKey="code" dataSource={data.redeem} columns={[{title:'Code',dataIndex:'code',render:v=><CodeLine text={v}/>},{title:'Plan',dataIndex:'plan_id',render:v=>planOptions(data.plans).find(o=>o.value===v)?.label||v},{title:'Status',dataIndex:'status',render:v=><StatusBadge status={v}/>},{title:'RedeemedBy',dataIndex:'redeemed_by_user_id'}]} /></Card></div>; }
function Tunnels({ data }) { return <Card bordered={false}><Table rowKey="id" dataSource={data.tunnels} columns={[{title:'ID',dataIndex:'id'},{title:'User',dataIndex:'user_id'},{title:'Name',dataIndex:'name'},{title:'Type',dataIndex:'type',render:v=><Tag color="blue">{v}</Tag>},{title:'Public',dataIndex:'public_url',render:v=>v?<CodeLine text={v}/>: '-'},{title:'Status',dataIndex:'status',render:v=><StatusBadge status={v}/>}]} /></Card>; }
function Nodes({ data, load, operation, setOperation }) { async function run(n, action, method='GET'){ setOperation({nodeName:n.name, action, status:'running', time:new Date(), output:'running...'}); try{ const out=await api.request(`/api/admin/nodes/${n.id}/${action}`, {method}); setOperation({nodeName:n.name, action, status:'success', time:new Date(), output:out}); await load(); }catch(e){ setOperation({nodeName:n.name, action, status:'failed', time:new Date(), output:e.message}); } } async function create(v){ try{ const node=await api.post('/api/admin/nodes', v); Modal.success({title:'NODE_BIND_TOKEN', content:<CodeLine text={node.bind_token}/>}); load(); }catch(e){message.error(e.message);} } return <div className="two-column"><Card title="FRPS 节点" bordered={false}><NodeCreate onCreate={create}/><Table rowKey="id" dataSource={data.nodes} columns={[{title:'ID',dataIndex:'id'},{title:'Name',dataIndex:'name'},{title:'Agent',dataIndex:'agent_url'},{title:'Status',dataIndex:'status',render:v=><StatusBadge status={v}/>},{title:'Action',render:(_,n)=><div className="node-action-grid">{[['status','GET','状态'],['frps-config','GET','配置'],['frps-logs','GET','日志'],['frps-restart','POST','重启'],['frps-reload','POST','Reload'],['nginx-test','POST','Nginx test'],['nginx-reload','POST','Nginx reload']].map(a=><Button size="small" key={a[0]} onClick={()=>run(n,a[0],a[1])}>{a[2]}</Button>)}</div>}]} /></Card><NodeOperationPanel operation={operation}/></div>; }
function NodeCreate({ onCreate }) { const [open,setOpen]=useState(false); const [form]=Form.useForm(); return <><Button type="primary" onClick={()=>{setOpen(true); form.setFieldsValue({frp_server_port:7000,tcp_port_start:20000,tcp_port_end:29999,udp_port_start:30000,udp_port_end:39999});}} style={{marginBottom:12}}>新增节点</Button><Drawer open={open} onClose={()=>setOpen(false)} title="新增 FRPS 节点" width={560}><Form form={form} layout="vertical" onFinish={(v)=>{onCreate(v); setOpen(false);}}><Form.Item name="name" label="Name" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="agent_url" label="Agent URL" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="public_url" label="Public URL"><Input/></Form.Item><Form.Item name="frp_entry_domain" label="FRP Entry Domain"><Input/></Form.Item><Form.Item name="server_addr" label="Server Addr"><Input/></Form.Item><Space wrap>{['frp_server_port','tcp_port_start','tcp_port_end','udp_port_start','udp_port_end'].map(k=><Form.Item key={k} name={k} label={k}><InputNumber/></Form.Item>)}</Space><Button type="primary" htmlType="submit">创建</Button></Form></Drawer></>; }
function Certificates({ data }) { async function post(path, body){ try{ const res=await api.post(path, body||{}); Modal.info({title:path, content:<pre>{JSON.stringify(res,null,2)}</pre>}); }catch(e){message.error(e.message);} } const [form]=Form.useForm(); return <div className="two-column"><Card title="证书操作" bordered={false}><Form form={form} layout="vertical"><Form.Item name="domain" label="Domain"><Input/></Form.Item><Form.Item name="target" label="CNAME Target"><Input/></Form.Item><Form.Item name="email" label="Email"><Input/></Form.Item><Space wrap><Button onClick={()=>post('/api/admin/domains/check-cname', form.getFieldsValue())}>CNAME</Button><Button onClick={()=>post('/api/admin/certificates/request', form.getFieldsValue())}>Request Cert</Button><Button onClick={()=>post('/api/admin/nginx/render-https', form.getFieldsValue())}>Render HTTPS</Button><Button onClick={()=>post('/api/admin/nginx/test')}>Nginx test</Button><Button onClick={()=>post('/api/admin/nginx/reload')}>Reload</Button><Button onClick={()=>post('/api/admin/certificates/renew-due',{force:false})}>Renew due</Button></Space></Form></Card><Card title="证书列表" bordered={false}><Table size="small" rowKey="id" dataSource={data.certs} columns={[{title:'Domain',dataIndex:'domain'},{title:'Status',dataIndex:'status',render:v=><StatusBadge status={v}/>},{title:'Expires',dataIndex:'expires_at',render:formatTime}]} /></Card></div>; }
function Settings({ data, load }) { const [form]=Form.useForm(); useEffect(()=>{ if(data.settings) form.setFieldsValue(data.settings); },[data.settings]); async function save(v){ try{ await api.put('/api/admin/settings', v); message.success('已保存'); load(); }catch(e){message.error(e.message);} } async function mail(){ try{ const res=await api.post('/api/admin/settings/test-mail',{email:form.getFieldValue('test_email')}); Modal.info({title:'Mail',content:JSON.stringify(res)}); }catch(e){message.error(e.message);} } return <div className="settings-grid"><Card title="系统设置" bordered={false}><Form form={form} layout="vertical" onFinish={save}>{['platform_domain','frp_entry_domain','server_addr','purchase_url'].map(k=><Form.Item key={k} name={k} label={k}><Input/></Form.Item>)}<Space wrap>{['frp_server_port','tcp_port_start','tcp_port_end','udp_port_start','udp_port_end'].map(k=><Form.Item key={k} name={k} label={k}><InputNumber/></Form.Item>)}</Space><Button type="primary" htmlType="submit">保存</Button></Form></Card><Card title="运维工具" bordered={false}><Space direction="vertical" style={{width:'100%'}}><Input placeholder="test@example.com" onChange={e=>form.setFieldValue('test_email',e.target.value)}/><Button onClick={mail}>发送测试邮件</Button><Descriptions column={1} bordered items={[{label:'Payment',children:<StatusBadge status={data.payment?.enabled?'online':'disabled'}/>},{label:'PID',children:data.payment?.pid_set?'set':'missing'},{label:'KEY',children:data.payment?.key_set?'set':'missing'},{label:'Submit URL',children:data.payment?.submit_url||'-'}]} /></Space></Card></div>; }
function Logs({ data }) { return <div className="two-column"><Card title="操作日志" bordered={false}><Table size="small" rowKey="id" dataSource={data.operations} columns={[{title:'Admin',dataIndex:'admin_email'},{title:'Action',dataIndex:'action'},{title:'Target',dataIndex:'target'},{title:'Time',dataIndex:'created_at',render:formatTime}]} /></Card><LogPanel title="运行输出" value={data.operations?.map(o=>`${o.created_at} ${o.action} ${o.target}`).join('\n')} /></div>; }
