
import React, { useEffect, useState } from 'react';
import { Alert, Button, Card, Descriptions, Form, Input, InputNumber, Select, Space, Steps, Table, Tag, Typography, message } from 'antd';
import { AppstoreOutlined, SyncOutlined, ControlOutlined, DeploymentUnitOutlined, ThunderboltOutlined, FileTextOutlined, SettingOutlined } from '@ant-design/icons';
import { AppShell } from '../../shared/frontend/components/AppShell.jsx';
import { MetricCard } from '../../shared/frontend/components/MetricCard.jsx';
import { StatusBadge } from '../../shared/frontend/components/StatusBadge.jsx';
import { LogPanel } from '../../shared/frontend/components/LogPanel.jsx';
import { CodeLine } from '../../shared/frontend/components/CopyText.jsx';
import { ApiClient, formatMbps, formatTime } from '../../shared/frontend/api/client.js';

const api = new ApiClient({ tokenKey: 'unused_local_token', localTokenKey: 'localApiToken' });
const routes = { status:['本机状态','本地 Client(FRPC) 和 frpc 运行状态'], sync:['配置同步','从 Master 拉取当前用户的 frpc 配置'], control:['frpc 控制','启动、停止、重启 frpc'], tunnels:['隧道列表','从 Master 预览当前用户隧道'], speed:['测速服务','本地 benchmark 和端到端测速'], logs:['日志','frpc 运行日志'], settings:['设置','API Server 和 Token 本地保存'] };
function route(){return location.hash.replace(/^#\/?/,'')||'status';}
function item(key,label,icon,shortLabel){return {key,label,rawLabel:label,shortLabel:shortLabel||label,icon};}
function localSetting(k, fallback=''){ return localStorage.getItem(k) || fallback; }
async function ensureLocalToken() {
  const current = localSetting('localApiToken', '');
  if (current) return current;
  const res = await fetch('/api/local-token');
  const json = await res.json();
  const token = json?.data?.token || '';
  if (token) localStorage.setItem('localApiToken', token);
  return token;
}
async function request(path, options={}) { await ensureLocalToken(); return api.request(path, options); }
export default function App(){ const [current,setCurrent]=useState(route()); const [state,setState]=useState({status:null,logs:'',config:'',tunnels:[]}); useEffect(()=>{const f=()=>setCurrent(route()); window.addEventListener('hashchange',f); return()=>window.removeEventListener('hashchange',f);},[]); async function load(){ try{ const [status, logs] = await Promise.all([request('/api/status').catch(()=>null), request('/api/logs').catch(()=>({logs:''}))]); setState(s=>({...s,status,logs:logs?.logs||''})); }catch{} } useEffect(()=>{load();},[]); const key=routes[current]?current:'status'; const menu=[{type:'group',label:'本机',children:[item('status','本机状态',<AppstoreOutlined/>,'本机状态'),item('sync','配置同步',<SyncOutlined/>,'配置同步'),item('control','frpc 控制',<ControlOutlined/>,'frpc')]},{type:'group',label:'隧道',children:[item('tunnels','隧道列表',<DeploymentUnitOutlined/>,'隧道列表'),item('speed','测速服务',<ThunderboltOutlined/>,'测速服务')]},{type:'group',label:'诊断',children:[item('logs','日志',<FileTextOutlined/>),item('settings','设置',<SettingOutlined/>)]}]; return <AppShell title={routes[key][0]} subtitle={routes[key][1]} brand="FRP Client" brandSub="Local FRPC" menuItems={menu} selectedKey={key} onSelect={k=>{location.hash=k; setCurrent(k);}} onRefresh={load} userLabel="Local" onLogout={()=>{}} storageKey="clientSidebarCollapsedV4">{render(key,state,setState,load)}</AppShell>; }
function render(key,state,setState,load){ const p={state,setState,load}; return ({status:<Status {...p}/>,sync:<ConfigSync {...p}/>,control:<Control {...p}/>,tunnels:<Tunnels {...p}/>,speed:<Speed {...p}/>,logs:<Logs {...p}/>,settings:<Settings {...p}/>})[key];}
function Status({state}){ const st=state.status||{}; return <div className="panel-stack"><Alert showIcon type={st.running?'success':'warning'} message={st.running?'frpc 运行中':'frpc 未运行'} description="Client(FRPC) 从 Master 拉取配置，启动 frpc 后连接 Server(FRPS)。"/><div className="metric-grid"><MetricCard title="frpc" value={st.running?'running':'stopped'} /><MetricCard title="PID" value={st.pid || '-'} /><MetricCard title="Started" value={st.started_at?formatTime(st.started_at):'-'} /><MetricCard title="Config" value={st.config_path?'ready':'missing'} /></div><Card bordered={false} title="本地路径"><Descriptions column={1} bordered items={[{label:'Config',children:<CodeLine text={st.config_path||'-'}/>},{label:'Log',children:<CodeLine text={st.log_path||'-'}/>}]} /></Card></div>; }
function Settings(){ const [form]=Form.useForm(); useEffect(()=>form.setFieldsValue({api_base:localSetting('apiBase','http://127.0.0.1:18188'),token:localSetting('userToken','')}),[]); function save(v){ localStorage.setItem('apiBase',v.api_base||''); localStorage.setItem('userToken',v.token||''); message.success('已保存'); } return <Card bordered={false}><Form form={form} layout="vertical" onFinish={save}><Form.Item name="api_base" label="API Server"><Input/></Form.Item><Form.Item name="token" label="User Token"><Input.Password/></Form.Item><Button type="primary" htmlType="submit">保存</Button></Form></Card>; }
function ConfigSync({state,setState,load}){ const [form]=Form.useForm(); useEffect(()=>form.setFieldsValue({api_base:localSetting('apiBase','http://127.0.0.1:18188'),token:localSetting('userToken','')}),[]); async function sync(v){ try{ localStorage.setItem('apiBase',v.api_base); localStorage.setItem('userToken',v.token); const res=await request('/api/config/sync',{method:'POST',body:{api_base:v.api_base,token:v.token}}); setState(s=>({...s,config:res.config||''})); message.success('同步完成'); await load(); }catch(e){message.error(e.message);} } return <div className="two-column"><Card title="配置同步" bordered={false}><Form form={form} layout="vertical" onFinish={sync}><Form.Item name="api_base" label="Master API"><Input/></Form.Item><Form.Item name="token" label="Token"><Input.Password/></Form.Item><Button type="primary" htmlType="submit">同步并生成 frpc.toml</Button></Form></Card><LogPanel title="frpc.toml" value={state.config} /></div>; }
function Control({load}){ async function op(path){ try{ const res=await request(path,{method:'POST'}); message.success('ok'); await load(); return res; }catch(e){message.error(e.message);} } return <Card bordered={false}><Space wrap><Button type="primary" onClick={()=>op('/api/frpc/start')}>启动 frpc</Button><Button onClick={()=>op('/api/frpc/restart')}>重启 frpc</Button><Button danger onClick={()=>op('/api/frpc/stop')}>停止 frpc</Button></Space><DividerLine/></Card>; }
function DividerLine(){ return <div style={{height:1,background:'#dbe4f0',margin:'16px 0'}}/>; }
function Tunnels({state,setState}){ const [form]=Form.useForm(); useEffect(()=>form.setFieldsValue({api_base:localSetting('apiBase','http://127.0.0.1:18188'),token:localSetting('userToken','')}),[]); async function preview(v){ try{ const res=await fetch(v.api_base.replace(/\/$/,'')+'/api/client/tunnels',{headers:{Authorization:'Bearer '+v.token}}); const json=await res.json(); if(!res.ok||json.success===false) throw new Error(json.message||res.statusText); setState(s=>({...s,tunnels:json.data.tunnels||[]})); }catch(e){message.error(e.message);} } return <Card bordered={false}><Form form={form} layout="inline" onFinish={preview} style={{marginBottom:16}}><Form.Item name="api_base"><Input placeholder="API Server"/></Form.Item><Form.Item name="token"><Input.Password placeholder="Token"/></Form.Item><Button type="primary" htmlType="submit">预览</Button></Form><Table rowKey="id" dataSource={state.tunnels} columns={[{title:'ID',dataIndex:'id'},{title:'Name',dataIndex:'name'},{title:'Type',dataIndex:'type',render:v=><Tag color="blue">{v}</Tag>},{title:'Public',dataIndex:'public_url'},{title:'Limit',dataIndex:'effective_bandwidth_limit_kbps',render:formatMbps},{title:'Status',dataIndex:'status',render:v=><StatusBadge status={v}/>}]} /></Card>; }
function Speed(){ const [form]=Form.useForm(); const [current,setCurrent]=useState(0); const [log,setLog]=useState(''); useEffect(()=>form.setFieldsValue({api_base:localSetting('apiBase','http://127.0.0.1:18188'),token:localSetting('userToken',''),type:'tcp',download_bytes:4*1024*1024,upload_bytes:2*1024*1024,duration_seconds:45}),[]); async function run(v){ try{ setCurrent(0); setLog('start'); const res=await request('/api/speed-tests/run',{method:'POST',body:v}); setCurrent(6); setLog(JSON.stringify(res,null,2)); }catch(e){setLog(e.message); message.error(e.message);} } return <div className="two-column"><Card title="端到端测速" bordered={false}><Form form={form} layout="vertical" onFinish={run}><Form.Item name="api_base" label="Master API"><Input/></Form.Item><Form.Item name="token" label="Token"><Input.Password/></Form.Item><Form.Item name="type" label="Type"><Select options={['tcp','udp','http','https'].map(v=>({value:v,label:v.toUpperCase()}))}/></Form.Item><Form.Item name="download_bytes" label="Download bytes"><InputNumber style={{width:'100%'}}/></Form.Item><Form.Item name="upload_bytes" label="Upload bytes"><InputNumber style={{width:'100%'}}/></Form.Item><Form.Item name="duration_seconds" label="Duration"><InputNumber style={{width:'100%'}}/></Form.Item><Button type="primary" htmlType="submit">开始测速</Button></Form></Card><div className="panel-stack"><Card bordered={false}><Steps current={current} direction="vertical" items={['prepare benchmark','create temp tunnel','sync temp config','restart frpc','API probe','restore config','cleanup'].map(title=>({title}))}/></Card><LogPanel value={log}/></div></div>; }
function Logs({state}){ return <LogPanel title="frpc.log" value={state.logs}/>; }
